[features]
seeds = true
[programs.localnet]
lockbox_governor = "DWDGo2UkBUFZ3VitBfWRBMvRnHr7E2DSh57NK27xMYaB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "artifacts/id.json"

[profile.release]
overflow-checks = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
